NOT WORKING


apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: app-rp-config-cm
data:  
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 4096;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        include /etc/nginx/conf.d/*.conf;

        # Settings for a TLS enabled server.
        #
        server {
            listen       80 http2;
            listen       [::]:80 http2;
            server_name  mykeycloak;
            root         /usr/share/nginx/html;

            # Load configuration files for the default server block.
            include /etc/nginx/default.d/*.conf;

            error_page 404 /404.html;
                location = /40x.html {
            }

            error_page 500 502 503 504 /50x.html;
                location = /50x.html {
            }
            
            location / {
          proxy_set_header Host                   $host;

              proxy_set_header X-Forwarded-For        $remote_addr;

              proxy_set_header X-Forwarded-Host       $host;
              # proxy_set_header X-Forwarded-Port       80;
              proxy_set_header X-Forwarded-Proto      $scheme;
              proxy_set_header X-Forwarded-Scheme     $scheme;

              proxy_set_header X-Scheme               $scheme;

              # Pass the original X-Forwarded-For
              proxy_set_header X-Original-Forwarded-For $http_x_forwarded_for;

              # mitigate HTTPoxy Vulnerability
              # https://www.nginx.com/blog/mitigating-the-httpoxy-vulnerability-with-nginx/
              proxy_set_header Proxy                  "";
        
              proxy_next_upstream                     error timeout;
              proxy_next_upstream_timeout             0;
              proxy_next_upstream_tries               3;
              proxy_redirect                          off;
              proxy_pass http://keycloak:8080;
          }
        }
    }
---
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: kc-proxy
  labels:
    app: kc-proxy
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: kc-proxy
  template:
    metadata:
      labels:
        app: kc-proxy
    spec:
      containers:
      - name: app-reverse-proxy
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-rp-config-cm-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - configMap:
          name: app-rp-config-cm
          items:
          - key: nginx.conf
            path: nginx.conf
        name: app-rp-config-cm-vol
---
apiVersion: v1
kind: Service
metadata:
  name: kc-proxy
spec:
  selector:
    app: kc-proxy
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 80
