apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: local-nginx-proxy
data:  
  nginx.conf: |
    server {
      listen       8083;
      server_name  localhost;
      location / {
          proxy_pass  http://keycloak:8080/;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
# ---
#       containers:
#       - name: kc-reverse-proxy
#         image: nginx
#         ports:
#         - containerPort: 8083
#         volumeMounts:
#         - name: local-nginx-proxy
#           mountPath: /etc/nginx/nginx.conf
#           subPath: nginx.conf
#           readOnly: true
#       volumes:
#       - configMap:
#           name: local-nginx-proxy
#           items:
#           - key: nginx.conf
#             path: nginx.conf
#         name: local-nginx-proxy-vol
